# Generated by Django 5.0.6 on 2024-08-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cilt_delete_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cilt',
        ),
    ]
